# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

__GUI_ver__ = "1.0.17"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        font = QtGui.QFont()
        font.setFamily("Arial")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        
###Main Window
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        MainWindow.setFont(font)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowTitle("API Campaign Manager")
        
###Central Widget
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
###Groupbox for filters=================================================
        self.groupBox_Filter = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Filter.setGeometry(QtCore.QRect(10, 0, 360, 100))
        self.groupBox_Filter.setObjectName("groupBox_Filter")
        self.groupBox_Filter.setTitle("Select filter")  
        
        font.setBold(False)
###Line 1
        self.line_1 = QtWidgets.QFrame(self.groupBox_Filter)
        self.line_1.setGeometry(QtCore.QRect(0, 15, 360, 2))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
###Line 2
        self.line_2 = QtWidgets.QFrame(self.groupBox_Filter)
        self.line_2.setGeometry(QtCore.QRect(0, 55, 360, 2))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")        
###Label Filter
        self.label_Filter = QtWidgets.QLabel(self.groupBox_Filter)
        self.label_Filter.setGeometry(QtCore.QRect(5, 15, 130, 15))
        self.label_Filter.setFont(font)
        self.label_Filter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Filter.setObjectName("label_Filter")
        self.label_Filter.setText("Filter")
###Label Condition
        self.label_Condition = QtWidgets.QLabel(self.groupBox_Filter)
        self.label_Condition.setGeometry(QtCore.QRect(140, 15, 80, 15))
        self.label_Condition.setFont(font)
        self.label_Condition.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Condition.setObjectName("label_Condition")
        self.label_Condition.setText("Condition")
###Label Value        
        self.label_Value = QtWidgets.QLabel(self.groupBox_Filter)
        self.label_Value.setGeometry(QtCore.QRect(225, 15, 130, 15))
        self.label_Value.setFont(font)
        self.label_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Value.setObjectName("label_Value")
        self.label_Value.setText("Value")
###Combobox Filter
        self.comboBox_Filter = QtWidgets.QComboBox(self.groupBox_Filter)
        self.comboBox_Filter.setGeometry(QtCore.QRect(5, 30, 130, 20))
        self.comboBox_Filter.setStyleSheet("border: 1px solid gray;")
        self.comboBox_Filter.setObjectName("comboBox_Filter")
        self.comboBox_Filter.addItem("NONE")
        self.comboBox_Filter.addItem("Campaign Enable")
        self.comboBox_Filter.addItem("Campaign Name")
        self.comboBox_Filter.addItem("Campaign Description")
        self.comboBox_Filter.addItem("Dialing Mode")
        self.comboBox_Filter.addItem("Lines Per Agent")
        self.comboBox_Filter.addItem("Maximum Lines Per Agent")
        self.comboBox_Filter.addItem("Minimum Call Duration")
        self.comboBox_Filter.addItem("Abandon Calls Limit Enable")
        self.comboBox_Filter.addItem("Abandon Calls Limit Percent")
        self.comboBox_Filter.addItem("Campaign Prefix Digits")
        self.comboBox_Filter.addItem("No Answer Ring Limit")
        self.comboBox_Filter.addItem("Maximum Attempts")
        self.comboBox_Filter.addItem("No Answer Delay")
        self.comboBox_Filter.addItem("Busy Signal Delay")
        self.comboBox_Filter.addItem("Customer Abandoned Delay")
        self.comboBox_Filter.addItem("Dialer Abandoned Delay")
        self.comboBox_Filter.addItem("Answering Machine Delay")
        self.comboBox_Filter.addItem("Personalized Callback")
        self.comboBox_Filter.addItem("Campaign Type")
        self.comboBox_Filter.addItem("Enable CPA")
        self.comboBox_Filter.addItem("Enable IP AMD")
        self.comboBox_Filter.addItem("Start Hours")
        self.comboBox_Filter.addItem("Start Minutes")
        self.comboBox_Filter.addItem("Start Date")
        self.comboBox_Filter.addItem("End Hours")
        self.comboBox_Filter.addItem("End Minutes")
        self.comboBox_Filter.addItem("End Date")
###Combobox Condition
        self.comboBox_Condition = QtWidgets.QComboBox(self.groupBox_Filter)
        self.comboBox_Condition.setEnabled(False)
        self.comboBox_Condition.setGeometry(QtCore.QRect(140, 30, 80, 20))
        self.comboBox_Condition.setStyleSheet("border: 1px solid gray;")
        self.comboBox_Condition.setObjectName("comboBox_Condition")
###Combobox Value        
        self.comboBox_Value = QtWidgets.QComboBox(self.groupBox_Filter)
        self.comboBox_Value.setEnabled(False)
        self.comboBox_Value.setEditable(True)
        self.comboBox_Value.setGeometry(QtCore.QRect(225, 30, 130, 20))
        self.comboBox_Value.setObjectName("comboBox_Value")
        self.comboBox_Value.setStyleSheet("QComboBox{border: 1px solid gray; background-color : white;}\n"
										"QComboBox::drop-down{border: 0px;}\n"
                                        "QComboBox::down-arrow{image: url(noimg);border-width: 0px;}")
###PushButton Retrieve
        self.pushButton_Retrieve = QtWidgets.QPushButton(self.groupBox_Filter)
        self.pushButton_Retrieve.setEnabled(False)
        self.pushButton_Retrieve.setGeometry(QtCore.QRect(225, 65, 110, 25))
        self.pushButton_Retrieve.setFont(font)
        self.pushButton_Retrieve.setObjectName("pushButton_Retrieve")
        self.pushButton_Retrieve.setText("&Retrieve")
###End Groupbox for filters=============================================

###Groupbox for Campaign List===========================================
        self.groupBox_Campaigns_List = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Campaigns_List.setGeometry(QtCore.QRect(10, 100, 360, 530))
        self.groupBox_Campaigns_List.setObjectName("groupBox_Campaigns_List")
        self.groupBox_Campaigns_List.setTitle("Campaigns List")
###ListWiwget Campaigns_List  
        self.listWidget_Campaigns_List = QtWidgets.QListWidget(self.groupBox_Campaigns_List)
        self.listWidget_Campaigns_List.setGeometry(QtCore.QRect(0, 20, 360, 510))
        self.listWidget_Campaigns_List.setFont(font)
        self.listWidget_Campaigns_List.setObjectName("listWidget_Campaigns_List")
###End Groupbox for Campaign List=======================================

###Group of buttons for Whole Campaign==================================
###Add button
        self.pushButton_Add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Add.setEnabled(False)
        self.pushButton_Add.setGeometry(QtCore.QRect(10, 635, 65, 25))
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.pushButton_Add.setText("&Add")
###Delete button        
        self.pushButton_Delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Delete.setEnabled(False)
        self.pushButton_Delete.setGeometry(QtCore.QRect(80, 635, 65, 25))
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.pushButton_Delete.setText("&Delete")
###Revert button        
        self.pushButton_Revert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Revert.setEnabled(False)
        self.pushButton_Revert.setGeometry(QtCore.QRect(150, 635, 65, 25))
        self.pushButton_Revert.setObjectName("pushButton_Revert")
        self.pushButton_Revert.setText("Revert")
###Save button        
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setEnabled(False)
        self.pushButton_Save.setGeometry(QtCore.QRect(220, 635, 65, 25))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_Save.setText("&Save")
###Close button
        self.pushButton_Close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Close.setGeometry(QtCore.QRect(290, 635, 65, 25))
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.pushButton_Close.setText("&Close")
        self.pushButton_Close.clicked.connect(QtWidgets.qApp.quit)
###End of Group buttons for Whole Campaign==============================        

###Groupbox for Campaign Detail=========================================
        self.groupBox_Campaigns_Detail = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Campaigns_Detail.setGeometry(QtCore.QRect(380, 0, 610, 660))
        self.groupBox_Campaigns_Detail.setObjectName("groupBox_Campaigns_Detail")
        self.groupBox_Campaigns_Detail.setTitle("Campaign Detail")
###Label Name
        self.label_Name = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_Name.setGeometry(QtCore.QRect(5, 20, 35, 20))
        self.label_Name.setFont(font)
        self.label_Name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Name.setObjectName("label_Name")
        self.label_Name.setText("Name:")
###LineEdit Name       
        self.lineEdit_Name = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_Name.setEnabled(False)
        self.lineEdit_Name.setGeometry(QtCore.QRect(40, 20, 300, 20))
        self.lineEdit_Name.setFont(font)
        self.lineEdit_Name.setMaxLength(32)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
###СheckBox Campaign_Enabled 
        self.checkBox_Campaign_Enabled = QtWidgets.QCheckBox(self.groupBox_Campaigns_Detail)
        self.checkBox_Campaign_Enabled.setEnabled(False)
        self.checkBox_Campaign_Enabled.setGeometry(QtCore.QRect(520, 20, 60, 20))
        self.checkBox_Campaign_Enabled.setFont(font)
        self.checkBox_Campaign_Enabled.setObjectName("checkBox_Campaign_Enabled") 
        self.checkBox_Campaign_Enabled.setText("Enabled")
###ComboBox Dialing_Mode 
        self.comboBox_Dialing_Mode = QtWidgets.QComboBox(self.groupBox_Campaigns_Detail)
        self.comboBox_Dialing_Mode.setEnabled(False)
        self.comboBox_Dialing_Mode.setGeometry(QtCore.QRect(380, 20, 130, 20))
        self.comboBox_Dialing_Mode.setFont(font)
        self.comboBox_Dialing_Mode.setObjectName("comboBox_Dialing_Mode")
        self.comboBox_Dialing_Mode.addItem("INBOUND")
        self.comboBox_Dialing_Mode.addItem("PREDICTIVEONLY")
        self.comboBox_Dialing_Mode.addItem("PREVIEWONLY")
        self.comboBox_Dialing_Mode.addItem("PROGRESSIVEONLY")
        self.comboBox_Dialing_Mode.addItem("PREVIEWDIRECTONLY")
        self.comboBox_Dialing_Mode.setCurrentText("INBOUND")
###Label Description
        self.label_Description = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_Description.setGeometry(QtCore.QRect(5, 45, 60, 20))
        self.label_Description.setFont(font)
        self.label_Description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Description.setObjectName("label_Description")
        self.label_Description.setText("Description:")
###Label Campaign_Type        
        self.label_Campaign_Type = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_Campaign_Type.setGeometry(QtCore.QRect(445, 45, 30, 20))
        self.label_Campaign_Type.setFont(font)
        self.label_Campaign_Type.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Campaign_Type.setObjectName("label_Campaign_Type")
        self.label_Campaign_Type.setText("Type:")
###ComboBox Campaign_Type
        self.comboBox_Campaign_Type = QtWidgets.QComboBox(self.groupBox_Campaigns_Detail)
        self.comboBox_Campaign_Type.setEnabled(False)
        self.comboBox_Campaign_Type.setGeometry(QtCore.QRect(480, 45, 100, 20))
        self.comboBox_Campaign_Type.setFont(font)
        self.comboBox_Campaign_Type.setObjectName("comboBox_Campaign_Type")
        self.comboBox_Campaign_Type.addItem("agentCampaign")
        self.comboBox_Campaign_Type.addItem("ivrCampaign")
        self.comboBox_Campaign_Type.setCurrentText("agentCampaign")
###LineEdit Description     
        self.lineEdit_Description = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_Description.setEnabled(False)
        self.lineEdit_Description.setGeometry(QtCore.QRect(70, 45, 375, 20))
        self.lineEdit_Description.setFont(font)
        self.lineEdit_Description.setMaxLength(255)
        self.lineEdit_Description.setObjectName("lineEdit_Description")
###Label Dialing_Mode
        self.label_Dialing_Mode = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_Dialing_Mode.setGeometry(QtCore.QRect(345, 20, 30, 20))
        self.label_Dialing_Mode.setFont(font)
        self.label_Dialing_Mode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Dialing_Mode.setObjectName("label_Dialing_Mode")
        self.label_Dialing_Mode.setText("Mode:")
###Label Lines
        self.label_Lines = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_Lines.setGeometry(QtCore.QRect(5, 70, 120, 20))
        self.label_Lines.setFont(font)
        self.label_Lines.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Lines.setObjectName("label_Lines")
        self.label_Lines.setText("Lines Per Agent (1-100):")
###LineEdit Lines 
        self.lineEdit_Lines = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_Lines.setEnabled(False)
        self.lineEdit_Lines.setGeometry(QtCore.QRect(130, 70, 40, 20))
        self.lineEdit_Lines.setFont(font)
        self.lineEdit_Lines.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Lines.setMaxLength(6)
        self.lineEdit_Lines.setObjectName("lineEdit_Lines")
###Label Max_Lines
        self.label_Max_Lines = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_Max_Lines.setGeometry(QtCore.QRect(175, 70, 165, 20))
        self.label_Max_Lines.setFont(font)
        self.label_Max_Lines.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Max_Lines.setObjectName("label_Max_Lines")
        self.label_Max_Lines.setText("Maximum Lines Per Agent (1-100):")
###LineEdit Max_Lines
        self.lineEdit_Max_Lines = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_Max_Lines.setEnabled(False)
        self.lineEdit_Max_Lines.setGeometry(QtCore.QRect(345, 70, 40, 20))
        self.lineEdit_Max_Lines.setFont(font)
        self.lineEdit_Max_Lines.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Max_Lines.setMaxLength(6)
        self.lineEdit_Max_Lines.setObjectName("lineEdit_Max_Lines")
###Label Prefix
        self.label_Prefix = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_Prefix.setGeometry(QtCore.QRect(395, 70, 60, 20))
        self.label_Prefix.setFont(font)
        self.label_Prefix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Prefix.setObjectName("label_Prefix")
        self.label_Prefix.setText("Prefix Digits:")
###LineEdit Prefix
        self.lineEdit_Prefix = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_Prefix.setEnabled(False)
        self.lineEdit_Prefix.setGeometry(QtCore.QRect(460, 70, 60, 20))
        self.lineEdit_Prefix.setFont(font)
        self.lineEdit_Prefix.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Prefix.setMaxLength(15)
        self.lineEdit_Prefix.setObjectName("lineEdit_Prefix")

###Groupbox for Abandon Parametres======================================
        self.groupBox_Aban_Limit = QtWidgets.QGroupBox(self.groupBox_Campaigns_Detail)
        self.groupBox_Aban_Limit.setGeometry(QtCore.QRect(5, 90, 600, 41))
        self.groupBox_Aban_Limit.setObjectName("groupBox_Aban_Limit")
        self.groupBox_Aban_Limit.setTitle("Abandon Limit")
###СheckBox Aban_Call_Limit         
        self.checkBox_Aban_Call_Limit = QtWidgets.QCheckBox(self.groupBox_Aban_Limit)
        self.checkBox_Aban_Call_Limit.setEnabled(False)
        self.checkBox_Aban_Call_Limit.setGeometry(QtCore.QRect(15, 15, 160, 20))
        self.checkBox_Aban_Call_Limit.setFont(font)
        self.checkBox_Aban_Call_Limit.setObjectName("checkBox_Aban_Call_Limit")
        self.checkBox_Aban_Call_Limit.setText("Abandon Call Limit (0-100%):")
###LineEdit Aban_Call_Limit        
        self.lineEdit_Aban_Call_Limit = QtWidgets.QLineEdit(self.groupBox_Aban_Limit)
        self.lineEdit_Aban_Call_Limit.setEnabled(False)
        self.lineEdit_Aban_Call_Limit.setFont(font)
        self.lineEdit_Aban_Call_Limit.setGeometry(QtCore.QRect(175, 15, 40, 20))
        self.lineEdit_Aban_Call_Limit.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Aban_Call_Limit.setMaxLength(6)
        self.lineEdit_Aban_Call_Limit.setObjectName("lineEdit_Aban_Call_Limit")
###Label Calls_Per_Adjustment
        self.label_Calls_Per_Adjustment = QtWidgets.QLabel(self.groupBox_Aban_Limit)
        self.label_Calls_Per_Adjustment.setGeometry(QtCore.QRect(220, 15, 155, 20))
        self.label_Calls_Per_Adjustment.setFont(font)
        self.label_Calls_Per_Adjustment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Calls_Per_Adjustment.setObjectName("label_Calls_Per_Adjustment")
        self.label_Calls_Per_Adjustment.setText("Calls Per Adjustment (10-5000):")
###LineEdit Calls_Per_Adjustment         
        self.lineEdit_Calls_Per_Adjustment = QtWidgets.QLineEdit(self.groupBox_Aban_Limit)
        self.lineEdit_Calls_Per_Adjustment.setEnabled(False)
        self.lineEdit_Calls_Per_Adjustment.setGeometry(QtCore.QRect(380, 15, 40, 20))
        self.lineEdit_Calls_Per_Adjustment.setFont(font)
        self.lineEdit_Calls_Per_Adjustment.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Calls_Per_Adjustment.setMaxLength(4)
        self.lineEdit_Calls_Per_Adjustment.setObjectName("lineEdit_Calls_Per_Adjustment")
###Label Max_Gain
        self.label_Max_Gain = QtWidgets.QLabel(self.groupBox_Aban_Limit)
        self.label_Max_Gain.setGeometry(QtCore.QRect(435, 15, 70, 20))
        self.label_Max_Gain.setFont(font)
        self.label_Max_Gain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Max_Gain.setObjectName("label_Max_Gain")
        self.label_Max_Gain.setText("Gain (0.1-3.0):")
###LineEdit Max_Gain        
        self.lineEdit_Max_Gain = QtWidgets.QLineEdit(self.groupBox_Aban_Limit)
        self.lineEdit_Max_Gain.setEnabled(False)
        self.lineEdit_Max_Gain.setGeometry(QtCore.QRect(510, 15, 30, 20))
        self.lineEdit_Max_Gain.setFont(font)
        self.lineEdit_Max_Gain.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_Max_Gain.setMaxLength(4)
        self.lineEdit_Max_Gain.setObjectName("lineEdit_Max_Gain")
###End Groupbox for Abandon Parametres==================================

###Groupbox Dial Settings===============================================
        self.groupBox_Dial_Settings = QtWidgets.QGroupBox(self.groupBox_Campaigns_Detail)
        self.groupBox_Dial_Settings.setGeometry(QtCore.QRect(5, 130, 600, 41))
        self.groupBox_Dial_Settings.setObjectName("groupBox_Dial_Settings")
        self.groupBox_Dial_Settings.setTitle("Dial Settings")
###Label No_Answer_Ring_Limit
        self.label_No_Answer_Ring = QtWidgets.QLabel(self.groupBox_Dial_Settings)
        self.label_No_Answer_Ring.setGeometry(QtCore.QRect(10, 15, 140, 20))
        self.label_No_Answer_Ring.setFont(font)
        self.label_No_Answer_Ring.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_No_Answer_Ring.setObjectName("label_No_Answer_Ring")
        self.label_No_Answer_Ring.setText("No Answer Ring Limit (2-10):")
###LineEdit No_Answer_Ring_Limit    
        self.lineEdit_No_Answe_Rin_Limit = QtWidgets.QLineEdit(self.groupBox_Dial_Settings)
        self.lineEdit_No_Answe_Rin_Limit.setEnabled(False)
        self.lineEdit_No_Answe_Rin_Limit.setGeometry(QtCore.QRect(155, 15, 30, 20))
        self.lineEdit_No_Answe_Rin_Limit.setFont(font)
        self.lineEdit_No_Answe_Rin_Limit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_No_Answe_Rin_Limit.setMaxLength(2)
        self.lineEdit_No_Answe_Rin_Limit.setObjectName("lineEdit_No_Answe_Rin_Limit")
###Label Maximum_Attempts
        self.label_Attempts = QtWidgets.QLabel(self.groupBox_Dial_Settings)
        self.label_Attempts.setGeometry(QtCore.QRect(190, 15, 130, 20))
        self.label_Attempts.setFont(font)
        self.label_Attempts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Attempts.setObjectName("label_Attempts")
        self.label_Attempts.setText("Maximum Attempts (1-100):")
###LineEdit Maximum_Attempts
        self.lineEdit_Attempts = QtWidgets.QLineEdit(self.groupBox_Dial_Settings)
        self.lineEdit_Attempts.setEnabled(False)
        self.lineEdit_Attempts.setGeometry(QtCore.QRect(325, 15, 30, 20))
        self.lineEdit_Attempts.setFont(font)
        self.lineEdit_Attempts.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Attempts.setMaxLength(3)
        self.lineEdit_Attempts.setObjectName("lineEdit_Attempts")
###Label Min_Call_Duration
        self.label_Min_Call_Duration = QtWidgets.QLabel(self.groupBox_Dial_Settings)
        self.label_Min_Call_Duration.setGeometry(QtCore.QRect(360, 15, 231, 20))
        self.label_Min_Call_Duration.setFont(font)
        self.label_Min_Call_Duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_Min_Call_Duration.setObjectName("label_Min_Call_Duration")
        self.label_Min_Call_Duration.setText("Minimum Call Duration (0-10):            Second(s)")
###LineEdit Min_Call_Duration
        self.lineEdit_Min_Call_Duration = QtWidgets.QLineEdit(self.groupBox_Dial_Settings)
        self.lineEdit_Min_Call_Duration.setEnabled(False)
        self.lineEdit_Min_Call_Duration.setGeometry(QtCore.QRect(515, 15, 30, 20))
        self.lineEdit_Min_Call_Duration.setFont(font)
        self.lineEdit_Min_Call_Duration.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Min_Call_Duration.setMaxLength(2)
        self.lineEdit_Min_Call_Duration.setObjectName("lineEdit_Min_Call_Duration")
###End Groupbox Dial Settings===========================================

###Personal Callback Settings===========================================
###СheckBox Pers_Callback
        self.checkBox_Pers_Callback = QtWidgets.QCheckBox(self.groupBox_Campaigns_Detail)
        self.checkBox_Pers_Callback.setEnabled(False)
        self.checkBox_Pers_Callback.setGeometry(QtCore.QRect(5, 175, 130, 20))
        self.checkBox_Pers_Callback.setFont(font)
        self.checkBox_Pers_Callback.setObjectName("checkBox_Pers_Callback")
        self.checkBox_Pers_Callback.setText("Personalized Callback:")
###Combobox Pers_Callback
        self.comboBox_Pers_Callback = QtWidgets.QComboBox(self.groupBox_Campaigns_Detail)
        self.comboBox_Pers_Callback.setEnabled(False)
        self.comboBox_Pers_Callback.setGeometry(QtCore.QRect(135, 175, 155, 20))
        self.comboBox_Pers_Callback.setFont(font)
        self.comboBox_Pers_Callback.setObjectName("comboBox_Pers_Callback")
        self.comboBox_Pers_Callback.addItem("useCampaignDN")
        self.comboBox_Pers_Callback.addItem("sameTimeNextBusinessDay")
        self.comboBox_Pers_Callback.addItem("abandon")        
        self.comboBox_Pers_Callback.setCurrentText("useCampaignDN")
###End Personal Callback Settings=======================================

###Groupbox Retries=====================================================
        self.groupBox_Retries = QtWidgets.QGroupBox(self.groupBox_Campaigns_Detail)
        self.groupBox_Retries.setGeometry(QtCore.QRect(5, 195, 175, 165))
        self.groupBox_Retries.setObjectName("groupBox_Retries")
        self.groupBox_Retries.setTitle("Retries (in minutes, 1-99999)")
###Label No_Answer_Delay        
        self.label_No_Answer_Delay = QtWidgets.QLabel(self.groupBox_Retries)
        self.label_No_Answer_Delay.setGeometry(QtCore.QRect(10, 15, 120, 20))
        self.label_No_Answer_Delay.setFont(font)
        self.label_No_Answer_Delay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_No_Answer_Delay.setObjectName("label_No_Answer_Delay")
        self.label_No_Answer_Delay.setText("No Answer Delay:")
###LineEdit No_Answer_Delay
        self.lineEdit_No_Answer_Delay = QtWidgets.QLineEdit(self.groupBox_Retries)
        self.lineEdit_No_Answer_Delay.setEnabled(False)
        self.lineEdit_No_Answer_Delay.setGeometry(QtCore.QRect(130, 15, 40, 20))
        self.lineEdit_No_Answer_Delay.setFont(font)
        self.lineEdit_No_Answer_Delay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_No_Answer_Delay.setMaxLength(5)
        self.lineEdit_No_Answer_Delay.setObjectName("lineEdit_No_Answer_Delay")        
###Label Busy_Delay         
        self.label_Busy_Delay = QtWidgets.QLabel(self.groupBox_Retries)
        self.label_Busy_Delay.setGeometry(QtCore.QRect(10, 40, 120, 20))
        self.label_Busy_Delay.setFont(font)
        self.label_Busy_Delay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Busy_Delay.setObjectName("label_Busy_Delay")
        self.label_Busy_Delay.setText("Busy Signal Delay:")
###LineEdit Busy_Delay
        self.lineEdit_Busy_Delay = QtWidgets.QLineEdit(self.groupBox_Retries)
        self.lineEdit_Busy_Delay.setEnabled(False)
        self.lineEdit_Busy_Delay.setGeometry(QtCore.QRect(130, 40, 40, 20))
        self.lineEdit_Busy_Delay.setFont(font)
        self.lineEdit_Busy_Delay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Busy_Delay.setMaxLength(5)
        self.lineEdit_Busy_Delay.setObjectName("lineEdit_Busy_Delay")        
###Label Customer_Aban_Delay
        self.label_Customer_Aban_Delay = QtWidgets.QLabel(self.groupBox_Retries)
        self.label_Customer_Aban_Delay.setGeometry(QtCore.QRect(10, 65, 120, 20))
        self.label_Customer_Aban_Delay.setFont(font)
        self.label_Customer_Aban_Delay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Customer_Aban_Delay.setObjectName("label_Customer_Aban_Delay")
        self.label_Customer_Aban_Delay.setText("Customer Aban. Delay:")
###LineEdit Customer_Aban_Delay
        self.lineEdit_Customer_Aban_Delay = QtWidgets.QLineEdit(self.groupBox_Retries)
        self.lineEdit_Customer_Aban_Delay.setEnabled(False)
        self.lineEdit_Customer_Aban_Delay.setGeometry(QtCore.QRect(130, 65, 40, 20))
        self.lineEdit_Customer_Aban_Delay.setFont(font)
        self.lineEdit_Customer_Aban_Delay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Customer_Aban_Delay.setMaxLength(5)
        self.lineEdit_Customer_Aban_Delay.setObjectName("lineEdit_Customer_Aban_Delay")        
###Label Dialer_Aban_Delay
        self.label_Dialer_Aban_Delay = QtWidgets.QLabel(self.groupBox_Retries)
        self.label_Dialer_Aban_Delay.setGeometry(QtCore.QRect(10, 90, 120, 20))
        self.label_Dialer_Aban_Delay.setFont(font)
        self.label_Dialer_Aban_Delay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Dialer_Aban_Delay.setObjectName("label_Dialer_Aban_Delay")
        self.label_Dialer_Aban_Delay.setText("Dialer Abandoned Delay:")
###LineEdit Dialer_Aban_Delay
        self.lineEdit_Dialer_Aban_Delay = QtWidgets.QLineEdit(self.groupBox_Retries)
        self.lineEdit_Dialer_Aban_Delay.setEnabled(False)
        self.lineEdit_Dialer_Aban_Delay.setGeometry(QtCore.QRect(130, 90, 40, 20))
        self.lineEdit_Dialer_Aban_Delay.setFont(font)
        self.lineEdit_Dialer_Aban_Delay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Dialer_Aban_Delay.setMaxLength(5)
        self.lineEdit_Dialer_Aban_Delay.setObjectName("lineEdit_Dialer_Aban_Delay")        
###Label AMD_Delay
        self.label_AMD_Delay = QtWidgets.QLabel(self.groupBox_Retries)
        self.label_AMD_Delay.setGeometry(QtCore.QRect(10, 115, 120, 20))
        self.label_AMD_Delay.setFont(font)
        self.label_AMD_Delay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_AMD_Delay.setObjectName("label_AMD_Delay")
        self.label_AMD_Delay.setText("AMD Delay:")
###LineEdit AMD_Delay
        self.lineEdit_AMD_Delay = QtWidgets.QLineEdit(self.groupBox_Retries)
        self.lineEdit_AMD_Delay.setEnabled(False)
        self.lineEdit_AMD_Delay.setGeometry(QtCore.QRect(130, 115, 40, 20))
        self.lineEdit_AMD_Delay.setFont(font)
        self.lineEdit_AMD_Delay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_AMD_Delay.setMaxLength(5)
        self.lineEdit_AMD_Delay.setObjectName("lineEdit_AMD_Delay")        
###Label Customer_Not_Home_Delay
        self.label_Customer_Home_Delay = QtWidgets.QLabel(self.groupBox_Retries)
        self.label_Customer_Home_Delay.setGeometry(QtCore.QRect(10, 140, 120, 20))
        self.label_Customer_Home_Delay.setFont(font)
        self.label_Customer_Home_Delay.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Customer_Home_Delay.setObjectName("label_Customer_Home_Delay")
        self.label_Customer_Home_Delay.setText("Not Home Delay:")
###LineEdit Customer_Not_Home_Delay
        self.lineEdit_Customer_Home_Delay = QtWidgets.QLineEdit(self.groupBox_Retries)
        self.lineEdit_Customer_Home_Delay.setEnabled(False)
        self.lineEdit_Customer_Home_Delay.setGeometry(QtCore.QRect(130, 140, 40, 20))
        self.lineEdit_Customer_Home_Delay.setFont(font)
        self.lineEdit_Customer_Home_Delay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Customer_Home_Delay.setMaxLength(5)
        self.lineEdit_Customer_Home_Delay.setObjectName("lineEdit_Customer_Home_Delay")
###End Groupbox Retries=================================================
        
###Groupbox for CPA=====================================================
        self.groupBox_CPA = QtWidgets.QGroupBox(self.groupBox_Campaigns_Detail)
        self.groupBox_CPA.setGeometry(QtCore.QRect(185, 195, 420, 160))
        self.groupBox_CPA.setObjectName("groupBox_CPA")
        self.groupBox_CPA.setTitle("CPA")
###СheckBox CPA_Enable
        self.checkBox_CPA_Enable = QtWidgets.QCheckBox(self.groupBox_CPA)
        self.checkBox_CPA_Enable.setEnabled(False)
        self.checkBox_CPA_Enable.setGeometry(QtCore.QRect(270, 10, 75, 20))
        self.checkBox_CPA_Enable.setFont(font)
        self.checkBox_CPA_Enable.setObjectName("checkBox_CPA_Enable")
        self.checkBox_CPA_Enable.setText("CPA Enable")
###СheckBox Record_CPA
        self.checkBox_Record_CPA = QtWidgets.QCheckBox(self.groupBox_CPA)
        self.checkBox_Record_CPA.setEnabled(False)
        self.checkBox_Record_CPA.setGeometry(QtCore.QRect(270, 30, 80, 20))
        self.checkBox_Record_CPA.setFont(font)
        self.checkBox_Record_CPA.setObjectName("checkBox_Record_CPA")
        self.checkBox_Record_CPA.setText("Record CPA")
###СheckBox IP_AMD_Enable
        self.checkBox_IP_AMD_Enable = QtWidgets.QCheckBox(self.groupBox_CPA)
        self.checkBox_IP_AMD_Enable.setEnabled(False)
        self.checkBox_IP_AMD_Enable.setGeometry(QtCore.QRect(270, 50, 90, 20))
        self.checkBox_IP_AMD_Enable.setFont(font)
        self.checkBox_IP_AMD_Enable.setObjectName("checkBox_IP_AMD_Enable")
        self.checkBox_IP_AMD_Enable.setText("Enable IP AMD")
###Groupbox IP_AMD======================================================
        self.groupBox_IP_AMD = QtWidgets.QGroupBox(self.groupBox_CPA)
        self.groupBox_IP_AMD.setGeometry(QtCore.QRect(270, 70, 145, 85))
        self.groupBox_IP_AMD.setObjectName("groupBox_IP_AMD")        
###RadioButton Aban_Call
        self.radioButton_Aban_Call = QtWidgets.QRadioButton(self.groupBox_IP_AMD)
        self.radioButton_Aban_Call.setEnabled(False)
        self.radioButton_Aban_Call.setGeometry(QtCore.QRect(5, 5, 110, 17))
        self.radioButton_Aban_Call.setFont(font)
        self.radioButton_Aban_Call.setChecked(True)
        self.radioButton_Aban_Call.setObjectName("radioButton_Aban_Call")
        self.radioButton_Aban_Call.setText("Abandon Call")
###RadioButton Transfer_to_Agent
        self.radioButton_Transfer_Agent = QtWidgets.QRadioButton(self.groupBox_IP_AMD)
        self.radioButton_Transfer_Agent.setEnabled(False)
        self.radioButton_Transfer_Agent.setGeometry(QtCore.QRect(5, 25, 110, 17))
        self.radioButton_Transfer_Agent.setFont(font)
        self.radioButton_Transfer_Agent.setObjectName("radioButton_Transfer_Agent")
        self.radioButton_Transfer_Agent.setText("Transfer to Agent")
###RadioButton Transfer_to_IVR
        self.radioButton_Transfer_IVR = QtWidgets.QRadioButton(self.groupBox_IP_AMD)
        self.radioButton_Transfer_IVR.setEnabled(False)
        self.radioButton_Transfer_IVR.setGeometry(QtCore.QRect(5, 45, 110, 17))
        self.radioButton_Transfer_IVR.setFont(font)
        self.radioButton_Transfer_IVR.setObjectName("radioButton_Transfer_IVR")
        self.radioButton_Transfer_IVR.setText("Transfer to IVR")
###СheckBox Terminate_Tone_Detect
        self.checkBox_Terminate_Tone_Detect = QtWidgets.QCheckBox(self.groupBox_IP_AMD)
        self.checkBox_Terminate_Tone_Detect.setEnabled(False)
        self.checkBox_Terminate_Tone_Detect.setGeometry(QtCore.QRect(15, 65, 130, 20))
        self.checkBox_Terminate_Tone_Detect.setFont(font)
        self.checkBox_Terminate_Tone_Detect.setObjectName("checkBox_Terminate_Tone_Detect")        
        self.checkBox_Terminate_Tone_Detect.setText("Terminate Tone Detect")        
###End Groupbox IP_AMD==================================================

###Groupbox CPA Parametres==============================================
        self.groupBox_CPA_Params = QtWidgets.QGroupBox(self.groupBox_CPA)
        self.groupBox_CPA_Params.setGeometry(QtCore.QRect(5, 15, 260, 140))
        self.groupBox_CPA_Params.setObjectName("groupBox_CPA_Params")
        self.groupBox_CPA_Params.setTitle("Parametres (in milliseconds)")
###Label Minimum_Silence_Period
        self.label_Minimum_Silence_Period = QtWidgets.QLabel(self.groupBox_CPA_Params)
        self.label_Minimum_Silence_Period.setGeometry(QtCore.QRect(10, 15, 195, 20))
        self.label_Minimum_Silence_Period.setFont(font)
        self.label_Minimum_Silence_Period.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Minimum_Silence_Period.setObjectName("label_Minimum_Silence_Period")
        self.label_Minimum_Silence_Period.setText("Minimum Silence Period (100-1000):")        
###LineEdit Minimum_Silence_Period
        self.lineEdit_Minimum_Silence_Period = QtWidgets.QLineEdit(self.groupBox_CPA_Params)
        self.lineEdit_Minimum_Silence_Period.setEnabled(False)
        self.lineEdit_Minimum_Silence_Period.setGeometry(QtCore.QRect(210, 15, 40, 20))
        self.lineEdit_Minimum_Silence_Period.setFont(font)
        self.lineEdit_Minimum_Silence_Period.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Minimum_Silence_Period.setMaxLength(4)
        self.lineEdit_Minimum_Silence_Period.setObjectName("lineEdit_Minimum_Silence_Period")        
###Label Analysis_Period
        self.label_Analysis_Period = QtWidgets.QLabel(self.groupBox_CPA_Params)
        self.label_Analysis_Period.setGeometry(QtCore.QRect(10, 40, 195, 20))
        self.label_Analysis_Period.setFont(font)
        self.label_Analysis_Period.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Analysis_Period.setObjectName("label_Analysis_Period")
        self.label_Analysis_Period.setText("Analysis Period (1000-10000):")        
###Label Analysis_Period
        self.lineEdit_Analysis_Period = QtWidgets.QLineEdit(self.groupBox_CPA_Params)
        self.lineEdit_Analysis_Period.setEnabled(False)
        self.lineEdit_Analysis_Period.setGeometry(QtCore.QRect(210, 40, 40, 20))
        self.lineEdit_Analysis_Period.setFont(font)
        self.lineEdit_Analysis_Period.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Analysis_Period.setMaxLength(5)
        self.lineEdit_Analysis_Period.setObjectName("lineEdit_Analysis_Period")
###Label Minimum_Valid_Speech
        self.label_Minimum_Valid_Speech = QtWidgets.QLabel(self.groupBox_CPA_Params)
        self.label_Minimum_Valid_Speech.setGeometry(QtCore.QRect(10, 65, 195, 20))
        self.label_Minimum_Valid_Speech.setFont(font)
        self.label_Minimum_Valid_Speech.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Minimum_Valid_Speech.setObjectName("label_Minimum_Valid_Speech")
        self.label_Minimum_Valid_Speech.setText("Minimum Valid Speech (50-500):")
###LineEdit Minimum_Valid_Speech
        self.lineEdit_Minimum_Valid_Speech = QtWidgets.QLineEdit(self.groupBox_CPA_Params)
        self.lineEdit_Minimum_Valid_Speech.setEnabled(False)
        self.lineEdit_Minimum_Valid_Speech.setGeometry(QtCore.QRect(210, 65, 40, 20))
        self.lineEdit_Minimum_Valid_Speech.setFont(font)
        self.lineEdit_Minimum_Valid_Speech.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Minimum_Valid_Speech.setMaxLength(3)
        self.lineEdit_Minimum_Valid_Speech.setObjectName("lineEdit_Minimum_Valid_Speech")        
###Label Maximum_Analysis_Time
        self.label_Maximum_Analysis_Time = QtWidgets.QLabel(self.groupBox_CPA_Params)
        self.label_Maximum_Analysis_Time.setGeometry(QtCore.QRect(10, 90, 195, 20))
        self.label_Maximum_Analysis_Time.setFont(font)
        self.label_Maximum_Analysis_Time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Maximum_Analysis_Time.setObjectName("label_Maximum_Analysis_Time")
        self.label_Maximum_Analysis_Time.setText("Maximum Analysis Time (1000-10000):")        
###LineEdit Maximum_Analysis_Time
        self.lineEdit_Maximum_Analysis_Time = QtWidgets.QLineEdit(self.groupBox_CPA_Params)
        self.lineEdit_Maximum_Analysis_Time.setEnabled(False)
        self.lineEdit_Maximum_Analysis_Time.setGeometry(QtCore.QRect(210, 90, 40, 20))
        self.lineEdit_Maximum_Analysis_Time.setFont(font)
        self.lineEdit_Maximum_Analysis_Time.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Maximum_Analysis_Time.setMaxLength(5)
        self.lineEdit_Maximum_Analysis_Time.setObjectName("lineEdit_Maximum_Analysis_Time")
###Label Maximum_Term_Tone_Analysis
        self.label_Maximum_Term_Tone_Analysis = QtWidgets.QLabel(self.groupBox_CPA_Params)
        self.label_Maximum_Term_Tone_Analysis.setGeometry(QtCore.QRect(10, 105, 195, 31))
        self.label_Maximum_Term_Tone_Analysis.setFont(font)
        self.label_Maximum_Term_Tone_Analysis.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Maximum_Term_Tone_Analysis.setObjectName("label_Maximum_Term_Tone_Analysis")
        self.label_Maximum_Term_Tone_Analysis.setText("Maximum Termination Tone Analysis\n"
        "(1000-60000):")
###LineEdit Maximum_Term_Tone_Analysis
        self.lineEdit_Maximum_Term_Tone_Analysis = QtWidgets.QLineEdit(self.groupBox_CPA_Params)
        self.lineEdit_Maximum_Term_Tone_Analysis.setEnabled(False)
        self.lineEdit_Maximum_Term_Tone_Analysis.setGeometry(QtCore.QRect(210, 115, 40, 20))
        self.lineEdit_Maximum_Term_Tone_Analysis.setFont(font)
        self.lineEdit_Maximum_Term_Tone_Analysis.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Maximum_Term_Tone_Analysis.setMaxLength(5)
        self.lineEdit_Maximum_Term_Tone_Analysis.setObjectName("lineEdit_Maximum_Term_Tone_Analysis")
###End Groupbox CPA Parametres==========================================
###End Groupbox for CPA=================================================

###Label TimeZone
        self.label_TimeZone = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_TimeZone.setGeometry(QtCore.QRect(5, 365, 50, 20))
        self.label_TimeZone.setFont(font)
        self.label_TimeZone.setAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_TimeZone.setObjectName("label_TimeZone")
        self.label_TimeZone.setText("TimeZone:")
###Combobox TimeZone
        self.comboBox_TimeZone = QtWidgets.QComboBox(self.groupBox_Campaigns_Detail)
        self.comboBox_TimeZone.setEnabled(False)
        self.comboBox_TimeZone.setGeometry(QtCore.QRect(65, 365, 540, 20))
        self.comboBox_TimeZone.setFont(font)
        self.comboBox_TimeZone.setObjectName("comboBox_TimeZone") 
 ###Label StartDate
        self.label_StartDate = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_StartDate.setGeometry(QtCore.QRect(5, 390, 50, 20))
        self.label_StartDate.setFont(font)
        self.label_StartDate.setAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_StartDate.setObjectName("label_StartDate")
        self.label_StartDate.setText("StartDate:")
###LineEdit StartDate
        self.lineEdit_StartDate = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_StartDate.setEnabled(False)
        self.lineEdit_StartDate.setGeometry(QtCore.QRect(60, 390, 65, 20))
        self.lineEdit_StartDate.setFont(font)
        self.lineEdit_StartDate.setMaxLength(10)
        self.lineEdit_StartDate.setObjectName("lineEdit_StartDate")
        self.lineEdit_StartDate.setInputMethodHints(QtCore.Qt.ImhDate)
###Label StartTime
        self.label_StartTime = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_StartTime.setGeometry(QtCore.QRect(130, 390, 50, 20))
        self.label_StartTime.setFont(font)
        self.label_StartTime.setAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_StartTime.setObjectName("label_StartTime")
        self.label_StartTime.setText("StartTime:")
###LineEdit StartTime
        self.lineEdit_StartTime = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_StartTime.setEnabled(False)
        self.lineEdit_StartTime.setGeometry(QtCore.QRect(185, 390, 65, 20))
        self.lineEdit_StartTime.setFont(font)
        self.lineEdit_StartTime.setMaxLength(5)
        self.lineEdit_StartTime.setObjectName("lineEdit_StartTime")
        self.lineEdit_StartTime.setInputMethodHints(QtCore.Qt.ImhTime)
###Label EndDate
        self.label_EndDate = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_EndDate.setGeometry(QtCore.QRect(250, 390, 50, 20))
        self.label_EndDate.setFont(font)
        self.label_EndDate.setAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EndDate.setObjectName("label_EndDate")
        self.label_EndDate.setText("EndDate:")
###LineEdit EndDate
        self.lineEdit_EndDate = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_EndDate.setEnabled(False)
        self.lineEdit_EndDate.setGeometry(QtCore.QRect(305, 390, 65, 20))
        self.lineEdit_EndDate.setFont(font)
        self.lineEdit_StartDate.setMaxLength(10)
        self.lineEdit_EndDate.setObjectName("lineEdit_EndDate")
        self.lineEdit_EndDate.setInputMethodHints(QtCore.Qt.ImhDate)
###Label EndTime
        self.label_EndTime = QtWidgets.QLabel(self.groupBox_Campaigns_Detail)
        self.label_EndTime.setGeometry(QtCore.QRect(370, 390, 50, 20))
        self.label_EndTime.setFont(font)
        self.label_EndTime.setAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EndTime.setObjectName("label_EndTime")
        self.label_EndTime.setText("EndTime:")
###LineEdit EndTime
        self.lineEdit_EndTime = QtWidgets.QLineEdit(self.groupBox_Campaigns_Detail)
        self.lineEdit_EndTime.setEnabled(False)
        self.lineEdit_EndTime.setGeometry(QtCore.QRect(425, 390, 65, 20))
        self.lineEdit_EndTime.setFont(font)
        self.lineEdit_EndTime.setMaxLength(5)
        self.lineEdit_EndTime.setObjectName("lineEdit_EndTime")
        self.lineEdit_EndTime.setInputMethodHints(QtCore.Qt.ImhTime)
 ###Groupbox for Skill Groups============================================
        self.groupBox_SG = QtWidgets.QGroupBox(self.groupBox_Campaigns_Detail)
        self.groupBox_SG.setGeometry(QtCore.QRect(0, 415, 610, 245))
        self.groupBox_SG.setObjectName("groupBox_SG")
        self.groupBox_SG.setTitle("Skill Groups")
###SG buttons===========================================================        
###PushButton Add_SG
        self.pushButton_Add_SG = QtWidgets.QPushButton(self.groupBox_SG)
        self.pushButton_Add_SG.setEnabled(False)
        self.pushButton_Add_SG.setGeometry(QtCore.QRect(80, 10, 65, 20))
        self.pushButton_Add_SG.setFont(font)
        self.pushButton_Add_SG.setObjectName("pushButton_Add_SG")
        self.pushButton_Add_SG.setText("Add")
###PushButton Remove_SG
        self.pushButton_Remove_SG = QtWidgets.QPushButton(self.groupBox_SG)
        self.pushButton_Remove_SG.setEnabled(False)
        self.pushButton_Remove_SG.setGeometry(QtCore.QRect(155, 10, 65, 20))
        self.pushButton_Remove_SG.setFont(font)
        self.pushButton_Remove_SG.setObjectName("pushButton_Remove_SG")
        self.pushButton_Remove_SG.setText("Remove")
###End SG buttons=======================================================
###Label Reservation Percentage
        self.label_Reserv_Percentage = QtWidgets.QLabel(self.groupBox_SG)
        self.label_Reserv_Percentage.setGeometry(QtCore.QRect(360, 10, 110, 20))
        self.label_Reserv_Percentage.setFont(font)
        self.label_Reserv_Percentage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Reserv_Percentage.setObjectName("label_Reserv_Percentage")
        self.label_Reserv_Percentage.setText("Reservation Percentage:")
###LineEdit Reservation Percentage
        self.lineEdit_Reserv_Percentage = QtWidgets.QLineEdit(self.groupBox_SG)
        self.lineEdit_Reserv_Percentage.setEnabled(False)
        self.lineEdit_Reserv_Percentage.setGeometry(QtCore.QRect(470, 10, 120, 20))
        self.lineEdit_Reserv_Percentage.setFont(font)
        self.lineEdit_Reserv_Percentage.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Reserv_Percentage.setMaxLength(3)
        self.lineEdit_Reserv_Percentage.setObjectName("lineEdit_Reserv_Percentage")
###tableWidget_SG
        self.tableWidget_SG = QtWidgets.QTableWidget(self.groupBox_SG)
        self.tableWidget_SG.setGeometry(QtCore.QRect(0, 35, 610, 210))
        self.tableWidget_SG.setSortingEnabled(False)
        font.setPointSize(7)
        self.tableWidget_SG.setFont(font)
        self.tableWidget_SG.setObjectName("tableWidget_SG")
        self.tableWidget_SG.setColumnCount(7)
        self.tableWidget_SG.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Name")
        self.tableWidget_SG.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Overflow Agents")
        self.tableWidget_SG.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Dialed Number")
        self.tableWidget_SG.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Records To Cache")
        self.tableWidget_SG.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("IVR Ports")
        self.tableWidget_SG.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("IVR RP")
        self.tableWidget_SG.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Aban. RP")
        self.tableWidget_SG.setHorizontalHeaderItem(6, item)
        self.tableWidget_SG.horizontalHeader().setDefaultSectionSize(84)  
        self.tableWidget_SG.horizontalHeader().setStyleSheet("QHeaderView::section{border-top:0px solid #D8D8D8;"
					"border-left:0px solid #D8D8D8;border-right:1px solid #D8D8D8;border-bottom: 1px solid #D8D8D8;"
					"background-color:white;padding:4px;}\n"
					"QTableCornerButton::section{border-top:0px solid #D8D8D8;border-left:0px solid #D8D8D8;"
					"border-right:1px solid #D8D8D8;border-bottom: 1px solid #D8D8D8;background-color:white;}")
     
###End Groupbox for Skill Groups========================================       
###End Groupbox for Campaign Detail=====================================
        
###Main Menu============================================================
        self.menufile = QtWidgets.QMenuBar(MainWindow)
        self.menufile.setFont(font)
        self.menufile.setObjectName("menufile")

        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setFont(font)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Exit.setText("&Exit (Ctrl+Q)")
        self.action_Exit.setShortcut('Ctrl+Q')
        self.action_Exit.setStatusTip('Exit')
        self.action_Exit.triggered.connect(QtWidgets.qApp.quit)

        self.menu_File = QtWidgets.QMenu(self.menufile)
        self.menu_File.setObjectName("menu_File")
        self.menu_File.setTitle("&File")
        self.menu_File.addAction(self.action_Exit)        

        self.action_Settings = QtWidgets.QAction(MainWindow)
        self.action_Settings.setFont(font)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Settings.setText("&Settings")

        self.menu_Connection = QtWidgets.QMenu(self.menufile)
        self.menu_Connection.setObjectName("menu_Connection")
        self.menu_Connection.setTitle("&Connection")
        self.menu_Connection.addAction(self.action_Settings)
        
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setFont(font)
        self.action_About.setObjectName("action_About")
        self.action_About.setText("&About")

        self.menu_Help = QtWidgets.QMenu(self.menufile)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Help.setTitle("&Help")
        self.menu_Help.addAction(self.action_About)
        
        self.menufile.addAction(self.menu_File.menuAction())
        self.menufile.addAction(self.menu_Connection.menuAction())
        self.menufile.addAction(self.menu_Help.menuAction())

###Statusbar============================================================
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

#Apply Bold to groupBoxes only==========================================
        font.setBold(True)
        self.groupBox_Filter.setFont(font)
        self.groupBox_Campaigns_List.setFont(font)
        self.groupBox_Campaigns_Detail.setFont(font)
        self.groupBox_Aban_Limit.setFont(font)
        self.groupBox_Dial_Settings.setFont(font)
        self.groupBox_Retries.setFont(font)
        self.groupBox_CPA.setFont(font)
        self.groupBox_CPA_Params.setFont(font)
        self.groupBox_SG.setFont(font)
#Apply Larger font to CampaignList=====================================
        font.setBold(False)
        font.setPointSize(font.pointSize()+2)
        self.listWidget_Campaigns_List.setFont(font)
###=====================================================================
        MainWindow.setCentralWidget(self.centralwidget)        
        MainWindow.setMenuBar(self.menufile)
        MainWindow.setStatusBar(self.statusbar)        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

class Connection_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog_Connection")
        Dialog.resize(310, 140)
        Dialog.setWindowTitle("Connection settings")
        Dialog.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(310, 140))
        Dialog.setMaximumSize(QtCore.QSize(310, 140))
        self.label_username = QtWidgets.QLabel(Dialog)
        self.label_username.setGeometry(QtCore.QRect(10, 10, 70, 30))
        self.label_username.setObjectName("label_username")
        self.label_username.setText("User name\n(FQDN):")        
        self.lineEdit_username = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(80, 10, 110, 20))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_atsign = QtWidgets.QLabel(Dialog)
        self.label_atsign.setGeometry(QtCore.QRect(190, 10, 15, 20))
        self.label_atsign.setObjectName("label_atsign") 
        self.label_atsign.setText("@")        
        self.lineEdit_domain = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_domain.setGeometry(QtCore.QRect(200, 10, 100, 20))
        self.lineEdit_domain.setObjectName("lineEdit_domain")
        self.label_pass = QtWidgets.QLabel(Dialog)
        self.label_pass.setGeometry(QtCore.QRect(10, 40, 70, 20))
        self.label_pass.setObjectName("label_pass")
        self.label_pass.setText("Password:")
        self.lineEdit_pass = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_pass.setGeometry(QtCore.QRect(80, 40, 220, 20))
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.lineEdit_pass.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)        
        self.label_server = QtWidgets.QLabel(Dialog)
        self.label_server.setGeometry(QtCore.QRect(10, 65, 70, 30))
        self.label_server.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_server.setObjectName("label_server")
        self.label_server.setText("Server\n(IP or FQDN):")        
        self.lineEdit_server = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_server.setGeometry(QtCore.QRect(80, 70, 220, 20))
        self.lineEdit_server.setObjectName("lineEdit_server")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 100, 90, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox_Save")
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox2 = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox2.setGeometry(QtCore.QRect(200, 100, 90, 32))
        self.buttonBox2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox2.setObjectName("buttonBox_Cancel")
        self.buttonBox2.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

class About_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog_About")
        Dialog.resize(400, 300)
        Dialog.setWindowTitle("About")
        Dialog.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 350, 220))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(20, 230, 350, 20))
        self.label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2.setObjectName("label2")        
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 340, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox_Ok")
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
